### ISSUE TITLE
The script doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by Anton-V-K** [MuromiU/JS#1]
Hi.
Thanks a lot for the script. It works just fine in all browsers except for ones produced by Microsoft (Microsoft Edge 38.14393, Internet Explorer 11.103.14393.0).
The error is: `Object doesn't support property or method 'forEach'`
The context:
```
  function Multi_languages()
  // Let over Lambda over Let over Lambda
  {
    let elements = new Map();
    let titles;
    let active_lang;
    let element_doms;
    return {
      init: function init()
      {
        element_doms = document.querySelectorAll('[lang]:not(title)');
        titles = document.querySelectorAll('title[lang]');
        return function (lang)
        {
          element_doms.forEach( // <=== ERROR
            function (element, _index)
            {
              if (!elements.has(element)) {
                elements.set(element, element.style.display);
              }
              if (element.lang != lang) {
                element.style.display = 'none';
              } else {
                element.style.display = elements.get(element);
                elements.delete(element);
              }
            });
          titles_container = titles[0].parentNode; // <title>s are special

```
So the elements aren't processed and all texts (in all languages) are visible.

**Comment by Anton-V-K** [comment]
The quick fix (from [here](http://tips.tutorialhorizon.com/2017/01/06/object-doesnt-support-property-or-method-foreach/)):
### The script to be added at global scope
```
(function () {
    if ( typeof NodeList.prototype.forEach === "function" ) return false;
    NodeList.prototype.forEach = Array.prototype.forEach;
})();
```

**Comment by ukari** [comment]
fixed, thank you for support.

**Comment by Anton-V-K** [comment]
It would be handy if the snippet to support `forEach` (for IE-based browsers) was included in your script, so it could work out of the box...

**Comment by ukari** [comment]
it is not a good practice to change the raw prototype method, so i won't change it.
Instead of this, I use a wrapper function to convert it in runtime, I thought the lastest code could works well on IE11

**Comment by Anton-V-K** [comment]
I wrote my commen without checking, sorry... Actually the recent `languages.js` works fine in IE as well as in other browsers. Thanks for the fix! :)

**Comment by ukari** [comment]
dont mind
