### ISSUE TITLE
Selected OPTION isn't handled properly for SELECT element

### ISSUE THREAD

**Issue by Anton-V-K** [MuromiU/JS#2]
I've encountered some issues when trying to translate `SELECT` element - the selected `OPTION` seems to ingore the `lang` attribute.

Here is the fragment:
```
         <select id='schedule_select'>
           <option lang='en' value='0' selected='true'>Manual</option>
           <option lang='ru' value='0' selected='true'>Ручной</option>
           <option lang='en' value='1'>Daily schedule</option>
           <option lang='ru' value='1'>Ежедневное расписание</option>
           <option lang='en' value='7'>Weekly schedule</option>
           <option lang='ru' value='7'>Недельное расписание</option>
         </select>
```
When the page with it is loaded, `en` is activated by default, however the SELECT element gets `ru` default value selected:
![select_lang](https://user-images.githubusercontent.com/20116984/34790931-0cfa4c6c-f64c-11e7-89de-9decb7736d96.png)
I expected it would show `Manual` as default value.

It happens in all browsers...

I also tried to change the approach with translation, and use several language-specific `span` elements within each `option`, but language is ignored in this case and all translated strings are shown together in each line...

What other alternatives to translate options for `SELECT` element?

**Comment by ukari** [comment]
resolved. Anton-V-K, thank you for supoort
