### ISSUE TITLE
When SELECT is assigned a value its language is reset to 1st one

### ISSUE THREAD

**Issue by Anton-V-K** [MuromiU/JS#3]
When I assign a value to `SELECT` element (from JavaScript), the language of the value is reset to the one which is declared first in HTML.
Probably related to #2

**Comment by ukari** [comment]
After `Languages.select("en")`

when i `schedule_select.value = "7"` the select shows `Weekly schedule`

when i `schedule_select.value = "1"` the select shows `Daily schedule`

could you give me a example which could re occur the problem?

**Comment by Anton-V-K** [comment]
Thanks for looking into this.
The English goes first in HTML definition (if you're using the sample from #2), so you should select another language (for instance, `ru`), and then change `SELECT` value: English string will be shown as selected, but Russian one is expected.

**Comment by ukari** [comment]
I add a commit to fix this, try it to see if there are still bug exist

**Comment by Anton-V-K** [comment]
I'v tried the fix. It solved the problem partialy, and has 2 negative side-effects:

1. After language change the value of `SELECT` is set to the first one (reset) - it should be kept.
2. If language switching is implemented via `SELECT`, it is not updated when new item is selected.

The previous version didn't have these issues...

I've attached sample page to test the behavior:
[test_schedule.htm.zip](https://github.com/MuromiU/JS/files/1682405/test_schedule.htm.zip)

**Comment by ukari** [comment]
I think the latest version should work with your example now

**Comment by Anton-V-K** [comment]
This issue seems to be fixed in the recent version :)
Thanks a lot for your efforts!
