### ISSUE TITLE
Problems with nested HTML-elements

### ISSUE THREAD

**Issue by Anton-V-K** [MuromiU/JS#4]
Here is HTML fragment which isn't displayed correctly:
```
         <button onclick='alert(this.innerHTML);'>
            <span lang='en' title='Hint in English'>EN <span class='fa fa-save' /></span>
            <span lang='ru' title='Подсказка по-русски'>RU <span class='fa fa-save' /></span>
            <span lang='ua' title='Подсказка по-украински'>UA <span class='fa fa-save' /></span>
         </button>
         <span style='border:1px solid red'>
            <span lang='en' title='Hint in English'>EN <i class='fa fa-save' /></span>
            <span lang='ru' title='Подсказка по-русски'>RU <i class='fa fa-save' /></span>
            <span lang='ua' title='Подсказка по-украински'>UA <i class='fa fa-save' /></span>
         </span>
```
`innerHTML` shows that hierarchy of nested elements is corrupted...
And nested `I` element isn't handled properly.
Could you please take a look?

**Comment by ukari** [comment]
I choose another method instead of re-sorting options in select to fix it, so nested HTML-elements in select won't matter

**Comment by Anton-V-K** [comment]
This issue seems to be fixed as well :)
The visual artefacts was partially caused by unexpected handling of `I` element without standalone closing tag, so the code `<i class='fa fa-save' />` drives modern browsers crazy...
The fragment should be re-written as `<i class='fa fa-save'></i>`, and everything is rendered smoothly now :)

**Comment by ukari** [comment]
fixed and closed, thank you for providing information
